"""Loader for Claude-authored SAT/ACT-style assessment items.

The gemma `style_gen` stage generates items live via Ollama; this loader instead
inserts curated, version-controlled items from a JSON seed
(`data/style_items.json`). Same DB shape as style_gen — a `style-gen-{style}`
source + `style-gen-{style}-math` book, `content_type='assessment'` chunks with
`item_generation='style_generated'`, and a `publisher_guide` alignment at 0.95 —
but the items are hand-authored (reviewable, reproducible, in git) and attributed
to Claude rather than Gemma.

Items are NOT copied from College Board or ACT materials; they are original
content modeled on those exams' style and rigor.

Usage:
    uv run python -m oer_ingestion.style_items --db data/oer_core.db
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

_DEFAULT_FILE = Path(__file__).parent / "data" / "style_items.json"

_EXAM_TO_STYLE = {"SAT": "sat", "ACT": "act"}


def _ensure_book(conn: sqlite3.Connection, style: str, exam_series: str, now: str) -> None:
    source_id = f"style-gen-{style}"
    conn.execute(
        """INSERT INTO sources (id, full_name, license, license_url, base_url, last_indexed)
           VALUES (?,?,?,?,?,?)
           ON CONFLICT(id) DO UPDATE SET last_indexed=excluded.last_indexed""",
        (
            source_id,
            f"{exam_series}-Style Questions (AI-Generated)",
            "CC BY 4.0",
            "https://creativecommons.org/licenses/by/4.0/",
            "https://github.com/swoopeagle/oer-mcp",
            now,
        ),
    )
    conn.execute(
        """INSERT INTO books (id, source_id, title, subject, grade_band, license, url)
           VALUES (?,?,?,?,?,?,?)
           ON CONFLICT(id) DO NOTHING""",
        (
            f"style-gen-{style}-math",
            source_id,
            f"{exam_series}-Style Math Questions (AI-Generated, K-12)",
            "mathematics",
            "K-12",
            "CC BY 4.0",
            "https://github.com/swoopeagle/oer-mcp",
        ),
    )


def load_style_items(conn: sqlite3.Connection, items_file: Path | str = _DEFAULT_FILE) -> dict[str, int]:
    """Upsert Claude-authored style items from a JSON seed. Idempotent: an item
    with the same standard/exam/question is skipped on re-run.
    Returns {'added', 'skipped'} counts."""
    data = json.loads(Path(items_file).read_text())
    items = data if isinstance(data, list) else data.get("items", [])
    now = datetime.now(timezone.utc).isoformat()
    added = skipped = 0
    books_ready: set[str] = set()

    for item in items:
        exam_series = item["exam_series"]
        style = _EXAM_TO_STYLE.get(exam_series)
        if style is None:
            raise ValueError(f"unknown exam_series {exam_series!r} (expected SAT or ACT)")
        if style not in books_ready:
            _ensure_book(conn, style, exam_series, now)
            books_ready.add(style)

        standard_id = item["standard_id"]
        question = item["question"].strip()
        source_id = f"style-gen-{style}"
        book_id = f"style-gen-{style}-math"
        uid = hashlib.sha256(
            f"{style}:{standard_id}:{question[:80]}".encode()
        ).hexdigest()[:12]
        chunk_id = f"style-{style}-{standard_id.replace('.', '_')}-{uid}"

        if conn.execute("SELECT 1 FROM chunks WHERE id=?", (chunk_id,)).fetchone():
            skipped += 1
            continue

        attribution = (
            f"AI-generated {exam_series}-style item for CCSS standard {standard_id}. "
            f"Generated by OER MCP using Claude. Not affiliated with or endorsed by "
            f"College Board or ACT. CC BY 4.0 (oer-mcp contributors)."
        )
        conn.execute(
            """INSERT INTO chunks
                 (id, book_id, source_id, title, content, content_type,
                  grade_band, word_count, source_url, attribution,
                  item_type, dok_level, answer_key, exam_series, exam_year,
                  difficulty, item_generation, content_hash, last_verified)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                chunk_id, book_id, source_id,
                f"{exam_series}-Style: {standard_id}", question, "assessment",
                item.get("grade_band"), len(question.split()),
                "https://github.com/swoopeagle/oer-mcp", attribution,
                item.get("item_type", "multiple_choice"), item.get("dok_level"),
                item.get("answer_key"), exam_series, None,
                item.get("difficulty"), "style_generated",
                hashlib.sha256(question.encode()).hexdigest(), now,
            ),
        )
        conn.execute(
            """INSERT INTO standard_alignments
                 (chunk_id, standard_id, standard_system, alignment_score,
                  alignment_source, coverage_notes)
               VALUES (?,?,?,?,?,?)
               ON CONFLICT(chunk_id, standard_id) DO NOTHING""",
            (
                chunk_id, standard_id, "ccss", 0.95, "publisher_guide",
                f"Claude-authored {exam_series}-style item directly assessing {standard_id}.",
            ),
        )
        added += 1

    conn.commit()
    return {"added": added, "skipped": skipped}


def main() -> None:
    from oer_shared.db import connect

    p = argparse.ArgumentParser(description="Load Claude-authored style items into the core DB")
    p.add_argument("--db", required=True, help="path to oer_core.db")
    p.add_argument("--file", default=str(_DEFAULT_FILE), help="items JSON (default: built-in seed)")
    args = p.parse_args()
    conn = connect(args.db, create=True)
    counts = load_style_items(conn, args.file)
    conn.close()
    print(f"[style_items] added={counts['added']} skipped={counts['skipped']}")


if __name__ == "__main__":
    main()
